name: Build PyQt5 App

on:
  push:
    branches:
      - local_version  # change to main once tested

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: uv sync

      - name: Build .dmg
        run: |
          uv run pyinstaller selecta.spec --noconfirm

      - name: Sign Code (for Apple)
        run: |
          codesign --deep --force --sign - dist/Selecta.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install Visual C++ Redistributable
        run: |
          choco install vcredist2015 -y

      - name: Install tensorflow
        run: |
          uv run pip install tensorflow

      - name: Install dependencies with uv
        run: uv sync

      - name: Build .exe
        run: |
          uv run pyinstaller selecta.spec --noconfirm

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist
